spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moviedb
    username: root
    password: 1995hakimov19
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080

